# Generated by Django 3.1.7 on 2021-03-16 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('PK_Category', models.AutoField(db_column='PK_Category', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nameCategory', max_length=100)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('PK_Manufacturer', models.AutoField(db_column='PK_Manufacturer', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nameBrand', max_length=100)),
            ],
            options={
                'db_table': 'Manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('PK_Puzzle', models.AutoField(db_column='PK_Puzzle', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name_of_puzzle', max_length=200)),
                ('number_of_details', models.IntegerField(db_column='number_of_details')),
                ('age', models.IntegerField(db_column='age')),
                ('ifalldetails', models.IntegerField(db_column='ifalldetails')),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('imagepath', models.ImageField(blank=True, db_column='imagePath', max_length=255, null=True, upload_to='')),
                ('PK_Category', models.ForeignKey(db_column='PK_Category', on_delete=django.db.models.deletion.DO_NOTHING, to='app.category')),
                ('PK_Manufacturer', models.ForeignKey(db_column='PK_Manufacturer', on_delete=django.db.models.deletion.DO_NOTHING, to='app.manufacturer')),
            ],
            options={
                'db_table': 'Puzzle',
            },
        ),
    ]
