# Generated by Django 3.1.7 on 2021-04-12 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='PK_Category',
            field=models.IntegerField(db_column='category'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='PK_Manufacturer',
            field=models.IntegerField(db_column='manufacturer'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='ifalldetails',
            field=models.BooleanField(db_column='ifalldetails'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='imagepath',
            field=models.ImageField(blank=True, db_column='imagePath', null=True, upload_to='photos'),
        ),
    ]
