# Generated by Django 3.1.7 on 2021-04-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210412_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='imagepath',
            field=models.ImageField(blank=True, db_column='imagepath', null=True, upload_to='photos'),
        ),
    ]
