# Generated by Django 3.1.7 on 2021-04-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210412_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzle',
            old_name='PK_Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='puzzle',
            old_name='PK_Manufacturer',
            new_name='manufacturer',
        ),
    ]
